[package]
name = "gray-scale"
version = "0.1.0"
authors = ["Stephen Becker IV <github@deathbyescalator.com>"]

[dependencies]
image = "*"
simple_parallel = "0.3"

[dependencies.rusoto]
features = ["s3"]
version = "*"
